// Define standard values for consistent data
export const STANDARD_VALUES = {
  BRANCHES: {
    COMMON: 'COMMON', // Added for first-year subjects that apply to all branches
    CHEMICAL: 'CHEMICAL',
    COMPUTER: 'COMPUTER',
    CIVIL: 'CIVIL',
    ENTC: 'ENTC',
    ETX: 'ETX',
    IT: 'IT',
    MECHANICAL: 'MECHANICAL'
  },
  YEARS: {
    FIRST_YEAR: 'FIRST YEAR',
    SECOND_YEAR: 'SECOND YEAR',
    THIRD_YEAR: 'THIRD YEAR',
    BTECH: 'BTECH'
  },
  EXAM_TYPES: {
    MSE: 'MSE',  // Mid Semester Exam
    ESE: 'ESE',  // End Semester Exam
    UT: 'UT',    // Unit Test
    CAT: 'CAT'   // Continuous Assessment Test
  },
  SEMESTERS: {
    SEM1: 'SEMESTER 1',
    SEM2: 'SEMESTER 2',
    SEM3: 'SEMESTER 3',
    SEM4: 'SEMESTER 4',
    SEM5: 'SEMESTER 5',
    SEM6: 'SEMESTER 6',
    SEM7: 'SEMESTER 7',
    SEM8: 'SEMESTER 8'
  },
  SUBJECTS: {
    // First Year Subjects
    ENGINEERING_MATHEMATICS_1: 'Engineering Mathematics 1',
    ENGINEERING_MATHEMATICS_2: 'Engineering Mathematics 2',
    ENGINEERING_PHYSICS: 'Engineering Physics',
    ENGINEERING_CHEMISTRY: 'Engineering Chemistry',
    BASIC_ELECTRICAL_ENGINEERING: 'Basic Electrical Engineering',
    COMPUTER_PROGRAMMING: 'Computer Programming',
    ENGINEERING_GRAPHICS: 'Engineering Graphics',
    APPLIED_MECHANICS: 'Applied Mechanics',
    LANGUAGE_COMMUNICATION: 'Language and Communication',
    
    // Computer Science Subjects
    DATA_STRUCTURES: 'Data Structures',
    DATABASE_SYSTEMS: 'Database Systems',
    OPERATING_SYSTEMS: 'Operating Systems',
    COMPUTER_NETWORKS: 'Computer Networks',
    
    // Mechanical Subjects
    MECHANICS: 'Mechanics',
    THERMODYNAMICS: 'Thermodynamics',
    
    // ENTC Subjects
    DIGITAL_ELECTRONICS: 'Digital Electronics',
    SIGNALS_SYSTEMS: 'Signals and Systems'
  }
} as const;

// Subject definitions with standard names and variations
export const SUBJECTS = {
  // First year common subjects - explicitly marked as common
  ENGINEERING_MATHEMATICS_1: {
    standard: 'Engineering Mathematics 1',
    variations: [
      'MATHEMATICS 1', 'MATHS 1', 'ENGINEERING MATHS 1', 'MATH-I', 'MATHEMATICS I', 'M1', 'MATHEMATICS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  ENGINEERING_MATHEMATICS_2: {
    standard: 'Engineering Mathematics 2',
    variations: [
      'MATHEMATICS 2', 'MATHS 2', 'ENGINEERING MATHS 2', 'MATH-II', 'MATHEMATICS II', 'M2'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM2
  },
  ENGINEERING_PHYSICS: {
    standard: 'Engineering Physics',
    variations: [
      'PHYSICS', 'APPLIED PHYSICS', 'ENGG. PHYSICS', 'ENGINEERING PHYSICS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  ENGINEERING_CHEMISTRY: {
    standard: 'Engineering Chemistry',
    variations: [
      'CHEMISTRY', 'APPLIED CHEMISTRY', 'ENGG. CHEMISTRY', 'ENGINEERING CHEMISTRY'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  BASIC_ELECTRICAL_ENGINEERING: {
    standard: 'Basic Electrical Engineering',
    variations: [
      'ELECTRICAL', 'ELECTRICAL ENGINEERING', 'BASIC ELECTRICAL', 'ELECTRICAL & ELECTRONICS',
      'ELECTRICAL AND ELECTRONICS', 'ELECTRICAL & ELECTRONICS ENGINEERING', 'ELECTRICAL AND ELECTRONICS ENGINEERING'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  COMPUTER_PROGRAMMING: {
    standard: 'Computer Programming',
    variations: [
      'PROGRAMMING', 'C PROGRAMMING', 'COMPUTER PROGRAM', 'PROGRAMMING CONCEPTS',
      'FUNDAMENTALS OF PROGRAMMING', 'PROGRAMMING FUNDAMENTALS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  ENGINEERING_GRAPHICS: {
    standard: 'Engineering Graphics',
    variations: [
      'GRAPHICS', 'ENGG GRAPHICS', 'ENGG. GRAPHICS', 'EG', 'DRAWING', 'ENGINEERING DRAWING'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  APPLIED_MECHANICS: {
    standard: 'Applied Mechanics',
    variations: [
      'MECHANICS', 'ENGINEERING MECHANICS', 'APPLIED MECH', 'MECH', 'BASIC MECHANICS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  LANGUAGE_COMMUNICATION: {
    standard: 'Language and Communication',
    variations: [
      'LANGUAGE', 'COMMUNICATION', 'LANGUAGE COMMUNICATION', 'ENGLISH', 'TECHNICAL ENGLISH',
      'COMMUNICATION SKILLS', 'TECHNICAL COMMUNICATION'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMMON,
    semester: STANDARD_VALUES.SEMESTERS.SEM1
  },
  
  // Computer Science subjects
  DATA_STRUCTURES: {
    standard: 'Data Structures',
    variations: [
      'DS', 'DATA STRUCTURE', 'DSA', 'DATA STRUCTURES AND ALGORITHMS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMPUTER,
    semester: STANDARD_VALUES.SEMESTERS.SEM3
  },
  DATABASE_SYSTEMS: {
    standard: 'Database Systems',
    variations: [
      'DB', 'DBMS', 'DATABASE', 'DATABASE MANAGEMENT', 'DATABASE MANAGEMENT SYSTEMS'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMPUTER,
    semester: STANDARD_VALUES.SEMESTERS.SEM4
  },
  OPERATING_SYSTEMS: {
    standard: 'Operating Systems',
    variations: [
      'OS', 'OPERATING SYSTEM'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMPUTER,
    semester: STANDARD_VALUES.SEMESTERS.SEM5
  },
  COMPUTER_NETWORKS: {
    standard: 'Computer Networks',
    variations: [
      'CN', 'NETWORKS', 'NETWORKING', 'COMPUTER NETWORK'
    ],
    branch: STANDARD_VALUES.BRANCHES.COMPUTER,
    semester: STANDARD_VALUES.SEMESTERS.SEM6
  },
  
  // Mechanical subjects
  MECHANICS: {
    standard: 'Mechanics',
    variations: [
      'ENGINEERING MECHANICS', 'APPLIED MECHANICS'
    ],
    branch: STANDARD_VALUES.BRANCHES.MECHANICAL,
    semester: STANDARD_VALUES.SEMESTERS.SEM3
  },
  THERMODYNAMICS: {
    standard: 'Thermodynamics',
    variations: [
      'THERMAL', 'THERMO', 'THERMAL ENGINEERING', 'ENGINEERING THERMODYNAMICS'
    ],
    branch: STANDARD_VALUES.BRANCHES.MECHANICAL,
    semester: STANDARD_VALUES.SEMESTERS.SEM4
  },
  
  // ENTC subjects
  DIGITAL_ELECTRONICS: {
    standard: 'Digital Electronics',
    variations: [
      'DE', 'DIGITAL', 'DIGITAL LOGIC', 'DIGITAL CIRCUITS'
    ],
    branch: STANDARD_VALUES.BRANCHES.ENTC,
    semester: STANDARD_VALUES.SEMESTERS.SEM3
  },
  SIGNALS_SYSTEMS: {
    standard: 'Signals and Systems',
    variations: [
      'SIGNALS', 'SYSTEMS', 'SIGNALS & SYSTEMS'
    ],
    branch: STANDARD_VALUES.BRANCHES.ENTC,
    semester: STANDARD_VALUES.SEMESTERS.SEM4
  }
};

// Branch variations mapping
export const branchMappings: Record<string, typeof STANDARD_VALUES.BRANCHES[keyof typeof STANDARD_VALUES.BRANCHES]> = {
  // Common variations for first year
  'FE': STANDARD_VALUES.BRANCHES.COMMON,
  'FY': STANDARD_VALUES.BRANCHES.COMMON,
  'F.Y': STANDARD_VALUES.BRANCHES.COMMON,
  'F Y': STANDARD_VALUES.BRANCHES.COMMON,
  'F.Y.': STANDARD_VALUES.BRANCHES.COMMON,
  'FIRST YEAR': STANDARD_VALUES.BRANCHES.COMMON,
  'FIRST-YEAR': STANDARD_VALUES.BRANCHES.COMMON,
  '1ST YEAR': STANDARD_VALUES.BRANCHES.COMMON,
  '1ST-YEAR': STANDARD_VALUES.BRANCHES.COMMON,
  'COMMON': STANDARD_VALUES.BRANCHES.COMMON,
  
  // Chemical variations
  'CH': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEM': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEMICAL': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEMICAL ENGINEERING': STANDARD_VALUES.BRANCHES.CHEMICAL,
  
  // Computer variations
  'CS': STANDARD_VALUES.BRANCHES.COMPUTER,
  'CSE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMP': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COM': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER SCIENCE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER ENGINEERING': STANDARD_VALUES.BRANCHES.COMPUTER,
  
  // Civil variations
  'CV': STANDARD_VALUES.BRANCHES.CIVIL,
  'CE': STANDARD_VALUES.BRANCHES.CIVIL,
  'CIVIL': STANDARD_VALUES.BRANCHES.CIVIL,
  'CIVIL ENGINEERING': STANDARD_VALUES.BRANCHES.CIVIL,
  
  // ENTC variations
  'ET': STANDARD_VALUES.BRANCHES.ENTC,
  'ENTC': STANDARD_VALUES.BRANCHES.ENTC,
  'E&TC': STANDARD_VALUES.BRANCHES.ENTC,
  'ELECTRONICS': STANDARD_VALUES.BRANCHES.ENTC,
  'ELECTRONICS AND TELECOMMUNICATION': STANDARD_VALUES.BRANCHES.ENTC,
  
  // ETX variations
  'EX': STANDARD_VALUES.BRANCHES.ETX,
  'ETX': STANDARD_VALUES.BRANCHES.ETX,
  
  // IT variations
  'IT': STANDARD_VALUES.BRANCHES.IT,
  'INFO': STANDARD_VALUES.BRANCHES.IT,
  'INFORMATION TECHNOLOGY': STANDARD_VALUES.BRANCHES.IT,
  
  // Mechanical variations
  'ME': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECH': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECHANICAL': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECHANICAL ENGINEERING': STANDARD_VALUES.BRANCHES.MECHANICAL
};

// First year detection patterns
export const firstYearPatterns = [
  /FE[-_\s.]?BTECH/i,
  /FIRST[\s-_.]?YEAR/i,
  /F[\s-_.]?Y[\s-_.]?/i,
  /^FY/i,
  /^FE/i,
  /1ST[\s-_.]?YEAR/i,
  /SEM[\s-_.]?[1I]/i,
  /SEMESTER[\s-_.]?[1I]/i
];

// Subject to branch mapping (backward compatibility)
export const subjectBranchMappings: Record<string, typeof STANDARD_VALUES.BRANCHES[keyof typeof STANDARD_VALUES.BRANCHES]> = {
  // First year common subjects
  'MATHEMATICS': STANDARD_VALUES.BRANCHES.COMMON,
  'PHYSICS': STANDARD_VALUES.BRANCHES.COMMON,
  'CHEMISTRY': STANDARD_VALUES.BRANCHES.COMMON,
  'ELECTRICAL': STANDARD_VALUES.BRANCHES.COMMON,
  'PROGRAMMING': STANDARD_VALUES.BRANCHES.COMMON,
  'GRAPHICS': STANDARD_VALUES.BRANCHES.COMMON,
  'MECHANICS': STANDARD_VALUES.BRANCHES.COMMON,
  'LANGUAGE': STANDARD_VALUES.BRANCHES.COMMON,
  'COMMUNICATION': STANDARD_VALUES.BRANCHES.COMMON,
  'ENGINEERING GRAPHICS': STANDARD_VALUES.BRANCHES.COMMON,
  'APPLIED MECHANICS': STANDARD_VALUES.BRANCHES.COMMON,
  
  // Mechanical subjects
  'SOLID MECHANICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'FLUID': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'DYNAMICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'KINEMATICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MANUFACTURING': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'ROBOTICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'AUTOMOBILE': STANDARD_VALUES.BRANCHES.MECHANICAL,
  
  // Chemical subjects
  'MATERIAL': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'MASS TRANSFER': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'HEAT TRANSFER': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'THERMODYNAMICS': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'REACTOR': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'PROCESS': STANDARD_VALUES.BRANCHES.CHEMICAL,
  
  // Computer subjects
  'DATABASE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'DATA STRUCTURES': STANDARD_VALUES.BRANCHES.COMPUTER,
  'OBJECT ORIENTED': STANDARD_VALUES.BRANCHES.COMPUTER,
  'OPERATING SYSTEM': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER NETWORK': STANDARD_VALUES.BRANCHES.COMPUTER,
  'SOFTWARE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'ALGORITHM': STANDARD_VALUES.BRANCHES.COMPUTER,
  'MACHINE LEARNING': STANDARD_VALUES.BRANCHES.COMPUTER,
  'ARTIFICIAL': STANDARD_VALUES.BRANCHES.COMPUTER,
  'CLOUD': STANDARD_VALUES.BRANCHES.COMPUTER,
  'WEB': STANDARD_VALUES.BRANCHES.COMPUTER,
  
  // ENTC subjects
  'ELECTRONICS': STANDARD_VALUES.BRANCHES.ENTC,
  'SIGNALS': STANDARD_VALUES.BRANCHES.ENTC,
  'COMM': STANDARD_VALUES.BRANCHES.ENTC,
  'DIGITAL': STANDARD_VALUES.BRANCHES.ENTC,
  'MICROPROCESSOR': STANDARD_VALUES.BRANCHES.ENTC,
  'ANTENNA': STANDARD_VALUES.BRANCHES.ENTC,
  'VLSI': STANDARD_VALUES.BRANCHES.ENTC,
  'EMBEDDED': STANDARD_VALUES.BRANCHES.ENTC,
  
  // Civil subjects
  'GEOTECHNICAL': STANDARD_VALUES.BRANCHES.CIVIL,
  'CONSTRUCTION': STANDARD_VALUES.BRANCHES.CIVIL,
  'ENVIRONMENTAL': STANDARD_VALUES.BRANCHES.CIVIL,
  'STRUCTURAL': STANDARD_VALUES.BRANCHES.CIVIL,
  'SURVEYING': STANDARD_VALUES.BRANCHES.CIVIL,
  'TRANSPORTATION': STANDARD_VALUES.BRANCHES.CIVIL,
  'CONCRETE': STANDARD_VALUES.BRANCHES.CIVIL,
  'STEEL': STANDARD_VALUES.BRANCHES.CIVIL,
  'HYDRAULICS': STANDARD_VALUES.BRANCHES.CIVIL
};

// Year variations
export const yearMappings: Record<string, typeof STANDARD_VALUES.YEARS[keyof typeof STANDARD_VALUES.YEARS]> = {
  // First year variations
  'FY': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'F Y': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'F.Y.': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FE': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FIRST YEAR': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FIRST': STANDARD_VALUES.YEARS.FIRST_YEAR,
  '1ST YEAR': STANDARD_VALUES.YEARS.FIRST_YEAR,
  '1ST': STANDARD_VALUES.YEARS.FIRST_YEAR,
  
  // Second year variations
  'SY': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'S Y': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'S.Y.': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SE': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SECOND YEAR': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SECOND': STANDARD_VALUES.YEARS.SECOND_YEAR,
  '2ND YEAR': STANDARD_VALUES.YEARS.SECOND_YEAR,
  '2ND': STANDARD_VALUES.YEARS.SECOND_YEAR,
  
  // Third year variations
  'TY': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'T Y': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'T.Y.': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'TE': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'THIRD YEAR': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'THIRD': STANDARD_VALUES.YEARS.THIRD_YEAR,
  '3RD YEAR': STANDARD_VALUES.YEARS.THIRD_YEAR,
  '3RD': STANDARD_VALUES.YEARS.THIRD_YEAR,
  
  // BTech variations
  'BTECH': STANDARD_VALUES.YEARS.BTECH,
  'B TECH': STANDARD_VALUES.YEARS.BTECH,
  'B.TECH': STANDARD_VALUES.YEARS.BTECH,
  'BACHELOR OF TECHNOLOGY': STANDARD_VALUES.YEARS.BTECH
};

// Exam type variations
export const examMappings: Record<string, typeof STANDARD_VALUES.EXAM_TYPES[keyof typeof STANDARD_VALUES.EXAM_TYPES]> = {
  // MSE variations
  'MSE': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MID SEM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MID TERM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MIDSEM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MIDTERM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'JUL': STANDARD_VALUES.EXAM_TYPES.MSE,
  'AUG': STANDARD_VALUES.EXAM_TYPES.MSE,
  'SEP': STANDARD_VALUES.EXAM_TYPES.MSE,
  'OCT': STANDARD_VALUES.EXAM_TYPES.MSE,
  
  // ESE variations
  'ESE': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END SEM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END TERM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'ENDSEM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'ENDTERM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END COURSE': STANDARD_VALUES.EXAM_TYPES.ESE,
  'JAN': STANDARD_VALUES.EXAM_TYPES.ESE,
  'FEB': STANDARD_VALUES.EXAM_TYPES.ESE,
  'MAR': STANDARD_VALUES.EXAM_TYPES.ESE,
  'APR': STANDARD_VALUES.EXAM_TYPES.ESE,
  'MAY': STANDARD_VALUES.EXAM_TYPES.ESE,
  'JUN': STANDARD_VALUES.EXAM_TYPES.ESE,
  'NOV': STANDARD_VALUES.EXAM_TYPES.ESE,
  'DEC': STANDARD_VALUES.EXAM_TYPES.ESE,
  'RE EXAM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'REEXAM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'RE-EXAM': STANDARD_VALUES.EXAM_TYPES.ESE,
  
  // Unit Test variations
  'UT': STANDARD_VALUES.EXAM_TYPES.UT,
  'UNIT TEST': STANDARD_VALUES.EXAM_TYPES.UT,
  'UNIT': STANDARD_VALUES.EXAM_TYPES.UT,
  
  // CAT variations
  'CAT': STANDARD_VALUES.EXAM_TYPES.CAT,
  'CYCLE TEST': STANDARD_VALUES.EXAM_TYPES.CAT,
  'CYCLE': STANDARD_VALUES.EXAM_TYPES.CAT,
  'CONTINUOUS ASSESSMENT': STANDARD_VALUES.EXAM_TYPES.CAT
};

// Semester standardization
export const semesterMappings: Record<string, typeof STANDARD_VALUES.SEMESTERS[keyof typeof STANDARD_VALUES.SEMESTERS]> = {
  // Roman numerals
  'I': STANDARD_VALUES.SEMESTERS.SEM1,
  'II': STANDARD_VALUES.SEMESTERS.SEM2,
  'III': STANDARD_VALUES.SEMESTERS.SEM3,
  'IV': STANDARD_VALUES.SEMESTERS.SEM4,
  'V': STANDARD_VALUES.SEMESTERS.SEM5,
  'VI': STANDARD_VALUES.SEMESTERS.SEM6,
  'VII': STANDARD_VALUES.SEMESTERS.SEM7,
  'VIII': STANDARD_VALUES.SEMESTERS.SEM8,
  
  // Numbers
  '1': STANDARD_VALUES.SEMESTERS.SEM1,
  '2': STANDARD_VALUES.SEMESTERS.SEM2,
  '3': STANDARD_VALUES.SEMESTERS.SEM3,
  '4': STANDARD_VALUES.SEMESTERS.SEM4,
  '5': STANDARD_VALUES.SEMESTERS.SEM5,
  '6': STANDARD_VALUES.SEMESTERS.SEM6,
  '7': STANDARD_VALUES.SEMESTERS.SEM7,
  '8': STANDARD_VALUES.SEMESTERS.SEM8,
  
  // Word variations
  'FIRST': STANDARD_VALUES.SEMESTERS.SEM1,
  'SECOND': STANDARD_VALUES.SEMESTERS.SEM2,
  'THIRD': STANDARD_VALUES.SEMESTERS.SEM3,
  'FOURTH': STANDARD_VALUES.SEMESTERS.SEM4,
  'FIFTH': STANDARD_VALUES.SEMESTERS.SEM5,
  'SIXTH': STANDARD_VALUES.SEMESTERS.SEM6,
  'SEVENTH': STANDARD_VALUES.SEMESTERS.SEM7,
  'EIGHTH': STANDARD_VALUES.SEMESTERS.SEM8,
  
  // Others
  'SEM 1': STANDARD_VALUES.SEMESTERS.SEM1,
  'SEM 2': STANDARD_VALUES.SEMESTERS.SEM2,
  'SEM 3': STANDARD_VALUES.SEMESTERS.SEM3,
  'SEM 4': STANDARD_VALUES.SEMESTERS.SEM4,
  'SEM 5': STANDARD_VALUES.SEMESTERS.SEM5,
  'SEM 6': STANDARD_VALUES.SEMESTERS.SEM6,
  'SEM 7': STANDARD_VALUES.SEMESTERS.SEM7,
  'SEM 8': STANDARD_VALUES.SEMESTERS.SEM8,
  'SEM-1': STANDARD_VALUES.SEMESTERS.SEM1,
  'SEM-2': STANDARD_VALUES.SEMESTERS.SEM2,
  'SEM-3': STANDARD_VALUES.SEMESTERS.SEM3,
  'SEM-4': STANDARD_VALUES.SEMESTERS.SEM4,
  'SEM-5': STANDARD_VALUES.SEMESTERS.SEM5,
  'SEM-6': STANDARD_VALUES.SEMESTERS.SEM6,
  'SEM-7': STANDARD_VALUES.SEMESTERS.SEM7,
  'SEM-8': STANDARD_VALUES.SEMESTERS.SEM8
};

// Subject mappings
export const subjectMappings: Record<string, string> = {
  // First Year Subject Mappings
  'MATHEMATICS 1': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'MATHS 1': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'ENGINEERING MATHS 1': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'MATH-I': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'MATHEMATICS I': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'M1': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,
  'MATHEMATICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_1,

  'MATHEMATICS 2': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,
  'MATHS 2': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,
  'ENGINEERING MATHS 2': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,
  'MATH-II': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,
  'MATHEMATICS II': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,
  'M2': STANDARD_VALUES.SUBJECTS.ENGINEERING_MATHEMATICS_2,

  'PHYSICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_PHYSICS,
  'APPLIED PHYSICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_PHYSICS,
  'ENGG. PHYSICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_PHYSICS,

  'CHEMISTRY': STANDARD_VALUES.SUBJECTS.ENGINEERING_CHEMISTRY,
  'APPLIED CHEMISTRY': STANDARD_VALUES.SUBJECTS.ENGINEERING_CHEMISTRY,
  'ENGG. CHEMISTRY': STANDARD_VALUES.SUBJECTS.ENGINEERING_CHEMISTRY,

  'ELECTRICAL': STANDARD_VALUES.SUBJECTS.BASIC_ELECTRICAL_ENGINEERING,
  'ELECTRICAL ENGINEERING': STANDARD_VALUES.SUBJECTS.BASIC_ELECTRICAL_ENGINEERING,
  'BASIC ELECTRICAL': STANDARD_VALUES.SUBJECTS.BASIC_ELECTRICAL_ENGINEERING,

  'PROGRAMMING': STANDARD_VALUES.SUBJECTS.COMPUTER_PROGRAMMING,
  'C PROGRAMMING': STANDARD_VALUES.SUBJECTS.COMPUTER_PROGRAMMING,
  'COMPUTER PROGRAM': STANDARD_VALUES.SUBJECTS.COMPUTER_PROGRAMMING,

  'GRAPHICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_GRAPHICS,
  'ENGG GRAPHICS': STANDARD_VALUES.SUBJECTS.ENGINEERING_GRAPHICS,
  'EG': STANDARD_VALUES.SUBJECTS.ENGINEERING_GRAPHICS,
  'DRAWING': STANDARD_VALUES.SUBJECTS.ENGINEERING_GRAPHICS,

  'MECHANICS': STANDARD_VALUES.SUBJECTS.APPLIED_MECHANICS,
  'ENGINEERING MECHANICS': STANDARD_VALUES.SUBJECTS.APPLIED_MECHANICS,
  'APPLIED MECH': STANDARD_VALUES.SUBJECTS.APPLIED_MECHANICS,

  'LANGUAGE': STANDARD_VALUES.SUBJECTS.LANGUAGE_COMMUNICATION,
  'COMMUNICATION': STANDARD_VALUES.SUBJECTS.LANGUAGE_COMMUNICATION,
  'ENGLISH': STANDARD_VALUES.SUBJECTS.LANGUAGE_COMMUNICATION,

  // Computer Science Subject Mappings
  'DS': STANDARD_VALUES.SUBJECTS.DATA_STRUCTURES,
  'DSA': STANDARD_VALUES.SUBJECTS.DATA_STRUCTURES,
  'DATA STRUCTURE': STANDARD_VALUES.SUBJECTS.DATA_STRUCTURES,

  'DB': STANDARD_VALUES.SUBJECTS.DATABASE_SYSTEMS,
  'DBMS': STANDARD_VALUES.SUBJECTS.DATABASE_SYSTEMS,
  'DATABASE': STANDARD_VALUES.SUBJECTS.DATABASE_SYSTEMS,

  'OS': STANDARD_VALUES.SUBJECTS.OPERATING_SYSTEMS,
  'OPERATING SYSTEM': STANDARD_VALUES.SUBJECTS.OPERATING_SYSTEMS,

  'CN': STANDARD_VALUES.SUBJECTS.COMPUTER_NETWORKS,
  'NETWORKS': STANDARD_VALUES.SUBJECTS.COMPUTER_NETWORKS,

  // Mechanical Subject Mappings
  'THERMO': STANDARD_VALUES.SUBJECTS.THERMODYNAMICS,
  'THERMAL': STANDARD_VALUES.SUBJECTS.THERMODYNAMICS,
  'THERMAL ENGINEERING': STANDARD_VALUES.SUBJECTS.THERMODYNAMICS,

  // ENTC Subject Mappings
  'DE': STANDARD_VALUES.SUBJECTS.DIGITAL_ELECTRONICS,
  'DIGITAL': STANDARD_VALUES.SUBJECTS.DIGITAL_ELECTRONICS,
  'DIGITAL LOGIC': STANDARD_VALUES.SUBJECTS.DIGITAL_ELECTRONICS,

  'SIGNALS': STANDARD_VALUES.SUBJECTS.SIGNALS_SYSTEMS,
  'SYSTEMS': STANDARD_VALUES.SUBJECTS.SIGNALS_SYSTEMS,
  'SIGNALS & SYSTEMS': STANDARD_VALUES.SUBJECTS.SIGNALS_SYSTEMS
}; 