// Define standard values first
export const STANDARD_VALUES = {
  BRANCHES: {
    CHEMICAL: 'CHEMICAL',
    COMPUTER: 'COMPUTER',
    CIVIL: 'CIVIL',
    ENTC: 'ENTC',
    ETX: 'ETX',
    IT: 'IT',
    MECHANICAL: 'MECHANICAL'
  },
  YEARS: {
    FIRST_YEAR: 'FIRST YEAR',
    SECOND_YEAR: 'SECOND YEAR',
    THIRD_YEAR: 'THIRD YEAR',
    BTECH: 'BTECH'
  },
  EXAM_TYPES: {
    MSE: 'MSE',
    ESE: 'ESE',
    UT: 'UT',
    CAT: 'CAT'
  }
} as const;

// Subject to branch mapping
export const subjectBranchMappings: Record<string, typeof STANDARD_VALUES.BRANCHES[keyof typeof STANDARD_VALUES.BRANCHES]> = {
  'ENGINEERING GRAPHICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'APPLIED MECHANICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'THERMAL': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'SOLID MECHANICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECHANICS': STANDARD_VALUES.BRANCHES.MECHANICAL,
  
  'CHEMISTRY': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'MATERIAL': STANDARD_VALUES.BRANCHES.CHEMICAL,
  
  'PROGRAMMING': STANDARD_VALUES.BRANCHES.COMPUTER,
  'DATABASE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'DATA STRUCTURES': STANDARD_VALUES.BRANCHES.COMPUTER,
  'OBJECT ORIENTED': STANDARD_VALUES.BRANCHES.COMPUTER,
  
  'ELECTRICAL': STANDARD_VALUES.BRANCHES.ENTC,
  'ELECTRONICS': STANDARD_VALUES.BRANCHES.ENTC,
  'SIGNALS': STANDARD_VALUES.BRANCHES.ENTC,
  'COMMUNICATION': STANDARD_VALUES.BRANCHES.ENTC,
  
  'PHYSICS': STANDARD_VALUES.BRANCHES.CIVIL,
  'GEOTECHNICAL': STANDARD_VALUES.BRANCHES.CIVIL,
  'CONSTRUCTION': STANDARD_VALUES.BRANCHES.CIVIL,
  'ENVIRONMENTAL': STANDARD_VALUES.BRANCHES.CIVIL
};

// Branch variations (multiple patterns can map to one standard value)
export const branchMappings: Record<string, typeof STANDARD_VALUES.BRANCHES[keyof typeof STANDARD_VALUES.BRANCHES]> = {
  // Chemical variations
  'CH': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEM': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEMICAL': STANDARD_VALUES.BRANCHES.CHEMICAL,
  'CHEMICAL ENGINEERING': STANDARD_VALUES.BRANCHES.CHEMICAL,
  
  // Computer variations
  'CS': STANDARD_VALUES.BRANCHES.COMPUTER,
  'CSE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMP': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COM': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER SCIENCE': STANDARD_VALUES.BRANCHES.COMPUTER,
  'COMPUTER ENGINEERING': STANDARD_VALUES.BRANCHES.COMPUTER,
  
  // Civil variations
  'CV': STANDARD_VALUES.BRANCHES.CIVIL,
  'CE': STANDARD_VALUES.BRANCHES.CIVIL,
  'CIVIL': STANDARD_VALUES.BRANCHES.CIVIL,
  'CIVIL ENGINEERING': STANDARD_VALUES.BRANCHES.CIVIL,
  
  // ENTC variations
  'ET': STANDARD_VALUES.BRANCHES.ENTC,
  'ENTC': STANDARD_VALUES.BRANCHES.ENTC,
  'E&TC': STANDARD_VALUES.BRANCHES.ENTC,
  'ELECTRONICS': STANDARD_VALUES.BRANCHES.ENTC,
  'ELECTRONICS AND TELECOMMUNICATION': STANDARD_VALUES.BRANCHES.ENTC,
  
  // ETX variations
  'EX': STANDARD_VALUES.BRANCHES.ETX,
  'ETX': STANDARD_VALUES.BRANCHES.ETX,
  
  // IT variations
  'IT': STANDARD_VALUES.BRANCHES.IT,
  'INFO': STANDARD_VALUES.BRANCHES.IT,
  'INFORMATION TECHNOLOGY': STANDARD_VALUES.BRANCHES.IT,
  
  // Mechanical variations
  'ME': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECH': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECHANICAL': STANDARD_VALUES.BRANCHES.MECHANICAL,
  'MECHANICAL ENGINEERING': STANDARD_VALUES.BRANCHES.MECHANICAL
};

// Year variations
export const yearMappings: Record<string, typeof STANDARD_VALUES.YEARS[keyof typeof STANDARD_VALUES.YEARS]> = {
  // First year variations
  'FY': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'F Y': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FE': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FIRST YEAR': STANDARD_VALUES.YEARS.FIRST_YEAR,
  'FIRST': STANDARD_VALUES.YEARS.FIRST_YEAR,
  '1ST YEAR': STANDARD_VALUES.YEARS.FIRST_YEAR,
  
  // Second year variations
  'SY': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'S Y': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SE': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SECOND YEAR': STANDARD_VALUES.YEARS.SECOND_YEAR,
  'SECOND': STANDARD_VALUES.YEARS.SECOND_YEAR,
  '2ND YEAR': STANDARD_VALUES.YEARS.SECOND_YEAR,
  
  // Third year variations
  'TY': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'T Y': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'TE': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'THIRD YEAR': STANDARD_VALUES.YEARS.THIRD_YEAR,
  'THIRD': STANDARD_VALUES.YEARS.THIRD_YEAR,
  '3RD YEAR': STANDARD_VALUES.YEARS.THIRD_YEAR,
  
  // BTech variations
  'BTECH': STANDARD_VALUES.YEARS.BTECH,
  'B TECH': STANDARD_VALUES.YEARS.BTECH,
  'B.TECH': STANDARD_VALUES.YEARS.BTECH,
  'BACHELOR OF TECHNOLOGY': STANDARD_VALUES.YEARS.BTECH
};

// Exam type variations
export const examMappings: Record<string, typeof STANDARD_VALUES.EXAM_TYPES[keyof typeof STANDARD_VALUES.EXAM_TYPES]> = {
  // MSE variations
  'MSE': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MID SEM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MID TERM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'MIDSEM': STANDARD_VALUES.EXAM_TYPES.MSE,
  'JUL': STANDARD_VALUES.EXAM_TYPES.MSE,
  'AUG': STANDARD_VALUES.EXAM_TYPES.MSE,
  'SEP': STANDARD_VALUES.EXAM_TYPES.MSE,
  'OCT': STANDARD_VALUES.EXAM_TYPES.MSE,
  
  // ESE variations
  'ESE': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END SEM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END TERM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'ENDSEM': STANDARD_VALUES.EXAM_TYPES.ESE,
  'END COURSE': STANDARD_VALUES.EXAM_TYPES.ESE,
  'JAN': STANDARD_VALUES.EXAM_TYPES.ESE,
  'FEB': STANDARD_VALUES.EXAM_TYPES.ESE,
  'MAR': STANDARD_VALUES.EXAM_TYPES.ESE,
  'APR': STANDARD_VALUES.EXAM_TYPES.ESE,
  'MAY': STANDARD_VALUES.EXAM_TYPES.ESE,
  'JUN': STANDARD_VALUES.EXAM_TYPES.ESE,
  'NOV': STANDARD_VALUES.EXAM_TYPES.ESE,
  'DEC': STANDARD_VALUES.EXAM_TYPES.ESE,
  
  // Unit Test variations
  'UT': STANDARD_VALUES.EXAM_TYPES.UT,
  'UNIT TEST': STANDARD_VALUES.EXAM_TYPES.UT,
  'UNIT': STANDARD_VALUES.EXAM_TYPES.UT,
  
  // CAT variations
  'CAT': STANDARD_VALUES.EXAM_TYPES.CAT,
  'CYCLE TEST': STANDARD_VALUES.EXAM_TYPES.CAT,
  'CYCLE': STANDARD_VALUES.EXAM_TYPES.CAT
};

// Semester standardization
export const semesterMappings: Record<string, string> = {
  // Roman numerals
  'I': 'SEMESTER 1',
  'II': 'SEMESTER 2',
  'III': 'SEMESTER 3',
  'IV': 'SEMESTER 4',
  'V': 'SEMESTER 5',
  'VI': 'SEMESTER 6',
  'VII': 'SEMESTER 7',
  'VIII': 'SEMESTER 8',
  
  // Numbers
  '1': 'SEMESTER 1',
  '2': 'SEMESTER 2',
  '3': 'SEMESTER 3',
  '4': 'SEMESTER 4',
  '5': 'SEMESTER 5',
  '6': 'SEMESTER 6',
  '7': 'SEMESTER 7',
  '8': 'SEMESTER 8',
  
  // Word variations
  'FIRST': 'SEMESTER 1',
  'SECOND': 'SEMESTER 2',
  'THIRD': 'SEMESTER 3',
  'FOURTH': 'SEMESTER 4',
  'FIFTH': 'SEMESTER 5',
  'SIXTH': 'SEMESTER 6',
  'SEVENTH': 'SEMESTER 7',
  'EIGHTH': 'SEMESTER 8'
}; 